language: generic
sudo: required

services:
  - docker

befroe_install:
  - docker build -t dolar/dokcer_ci_cd_aws -f Dockerfile.dev .

script:
  - docker run -e CI=true dolar/dokcer_ci_cd_aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "ci_cd_aws"
  env: "CiCdAws-env"
  bucket_name: "elasticbeanstalk-ap-south-1-700730497016"
  bucket_path: "ci_cd_aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#   =========================
#   EARLIER....
# script:
#     - docker run USERNAME/docker-react npm run test -- --coverage

#   CHANGED TO....
# script:
#     - docker run -e CI=true USERNAME/docker-react npm run test

# ========================================
# STEPS TO RUN TESTS..........
# docker run -it dolar/react_ci_cd npm run test
# ANOTHER WAY...........
